### ISSUE TITLE
Functions that we need to do.

### ISSUE THREAD

**Issue by zokatr** [xFireBerg/BIM470_Project#2]
- [x] -  initialize_parameters_and_layer_sizes()
- [x] -  forward_propagation()
- [x] -  compute_cost()
- [x] -  update_parameters()
- [x] -  backward_propagation()
- [x] -  predict()
- [ ] -  train(x_train, y_train,x_test,y_test, num_iterations)

These are some functions idea that can be helpful for management the code.

**Comment by xFireBerg** [comment]
The flatten operation needs to be adjusted for multilayered filters, plus the operations after it (Vout, Vhidden, softmax) need adjusting and forward propagation would be done

**Comment by zokatr** [comment]
> The flatten operation needs to be adjusted for multilayered filters, plus the operations after it (Vout, Vhidden, softmax) need adjusting and forward propagation would be done

Check last commit, is there anything to do for forward.
